
  [
  {
  "id": 101,
  "first": "meseret",
  "last": "un",
  "department": "mule"
  },
  {
  "id": 102,
  "first": "endale",
  "last": "Dj",
  "department": "salesforce"
  },
  {
  "id": 102,
  "first": "Bereket",
  "last": "Dere",
  "department": "salesforce"
  }
]