#%RAML 1.0 NamedExample
POST_USER_REQUEST:
  [
  {
  "id": 1,
  "first": "Bekele",
  "last": "Abebe",
  "department": "Mulesoft"
  },
  {
  "id": 3,
  "first": "Admke",
  "last": "Dereje",
  "department": "Salesforce"
  }
]
